{
 "title": "OLT Fiberhome Bela Vista",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "slot", "label": "Slot", "query": "1, 2, 3, 4" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"container\">\r\n        <div class=\"text\">MONITORAMENTO OLT BELA VISTA</div>\r\n        <div class=\"logoTp\">\r\n            <img src=\"https://i.imgur.com/lt7ZeST.png\"\r\n     alt=\"TriplePLay\"\r\n     width=\"300\">\r\n\r\n        </div>\r\n    </div>\r\n<style>\r\n    .text{\r\n    font-family: Arial, Helvetica, sans-serif;\r\nfont-size: 27px;\r\nletter-spacing: 2px;\r\nword-spacing: 2px;\r\ncolor: #fff;\r\nfont-weight: 700;\r\ntext-decoration: none;\r\nfont-style: italic;\r\nfont-variant: small-caps;\r\ntext-transform: none;\r\n    }\r\n\r\n    .container{\r\n   \r\n    height:6em;\r\n\r\n    display: flex;\r\n    flex-direction: row;\r\n    \r\n    align-items: center;\r\n    justify-content: space-evenly;\r\n\r\n   \r\n    \r\nbackground: rgba(255, 255, 255, 0.35);\r\nborder-radius: 16px;\r\nbox-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);\r\nbackdrop-filter: blur(7.1px);\r\n-webkit-backdrop-filter: blur(7.1px);\r\nborder: 1px solid rgba(255, 255, 255, 0.4);\r\n\r\n    \r\n\r\n}\r\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Download" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "CPN-BNG-JUNIPER-MX80" },
     "item": {
      "filter": "Interface [xe-0/0/1][OLT-FIBERHOME-BELA-VISTA]: Bits sent"
     },
     "itemTag": {
      "filter": "alias: OLT-FIBERHOME-BELA-VISTA"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CONSUMO GERAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(24h)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Download - Ontem" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "CPN-BNG-JUNIPER-MX80" },
     "item": {
      "filter": "Interface [xe-0/0/1][OLT-FIBERHOME-BELA-VISTA]: Bits sent"
     },
     "itemTag": {
      "filter": "alias: OLT-FIBERHOME-BELA-VISTA"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Download" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "CPN-BNG-JUNIPER-MX80" },
     "item": {
      "filter": "Interface [xe-0/0/1][OLT-FIBERHOME-BELA-VISTA]: Bits sent"
     },
     "itemTag": {
      "filter": "alias: OLT-FIBERHOME-BELA-VISTA"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Upload" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "CPN-BNG-JUNIPER-MX80" },
     "item": {
      "filter": "Interface [xe-0/0/1][OLT-FIBERHOME-BELA-VISTA]: Bits received"
     },
     "itemTag": {
      "filter": "alias: OLT-FIBERHOME-BELA-VISTA"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Upload" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "CPN-BNG-JUNIPER-MX80" },
     "item": {
      "filter": "Interface [xe-0/0/1][OLT-FIBERHOME-BELA-VISTA]: Bits received"
     },
     "itemTag": {
      "filter": "alias: OLT-FIBERHOME-BELA-VISTA"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ONLINE" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "OLT-FIBERHOME-BELA-VISTA" },
     "item": { "filter": "Total ONUs Online (Global)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PROVISIONADAS" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "OLT-FIBERHOME-BELA-VISTA" },
     "item": {
      "filter": "Total ONUs Provisionadas (Global)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OFFLINE" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "OLT-FIBERHOME-BELA-VISTA" },
     "item": { "filter": "Total ONUs Offline (Global)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "MÉDIA DE SINAL",
   "type": "stat",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(?![0-9]+\\/[0-9]+\\/[0-9]+)[A-Za-zé\\-\\(\\)\\_\\: ]+/",
        "PON "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\\-\\(\\)/",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "OLT-FIBERHOME-BELA-VISTA" },
     "item": {
      "filter": "/^Média Sinal dBm - PON (${slot:regex})\\/[0-9]+(\\/[0-9]+)?$/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "USO DAS PONS",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\\-\\(\\)/",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(?![0-9]+\\/[0-9]+\\/[0-9]+)[A-Za-zé\\-\\(\\)\\_\\: ]+/",
        "PON "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "COOPERNET" },
     "host": { "filter": "OLT-FIBERHOME-BELA-VISTA" },
     "item": {
      "filter": "/^ONUs Provisionadas - PON (${slot:regex})\\/[0-9]+(\\/[0-9]+)?$/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<style>\n\nbody{\n\n    margin: auto;\n    font-family: -apple-system, BlinkMacSystemFont, sans-serif;\n    overflow: auto;\n    background: linear-gradient(315deg, #104443 3%, #185971 38%, #1b617a 68%, #104443 98%);\n    animation: gradient 15s ease infinite;\n    background-size: 400% 400%;\n    background-attachment: fixed;\n\n\n\n\n}\n\n@keyframes gradient {\n    0% {\n        background-position: 0% 0%;\n    }\n    50% {\n        background-position: 100% 100%;\n    }\n    100% {\n        background-position: 0% 0%;\n    }\n}\n\n.css-19gv2o1-panel-header{\n\nbackground: rgb(2,0,36);\nbackground: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 26%, rgba(0,212,255,1) 100%);\n\nborder-radius: 0px 66px 0px 66px;\n-webkit-border-radius: 0px 66px 0px 66px;\n-moz-border-radius: 0px 66px 0px 66px;\n\ndisplay: flex;\nflex-direction: column;\njustify-content: center;\nalign-items: center;\n}\n\n.css-1bo04y5-panel-title {\n\ntext-align: center;\ntext-size:50px;\nheight: 60em;\npadding-bottom: 2.5em;\npadding-top: 1.5em;\n\nfont-size:24px;\n\n}\n\n\n\n.css-kvzgb9-panel-content{\nborder: .0px solid #000000;\n}\n\n</style>"
   }
  }
 ]
}